---
format: 
  html:
    css: styles.css
---

# 1-2. UX 디자인과 데이터, AI

### 데이터의 시각으로 해석한 디자인

UX 디자인에서 데이터를 사용하는 것은 새로운 현상이 아닙니다. 디자인 과정에서 데이터는 언제나 사용되어 왔습니다. 우리가 수행하는 디자인 리서치는 대부분 디자인 주제와 관련한 데이터를 수집하는 것으로 시작됩니다. 그리고 디자이너는 수집한 데이터를 검토하여 필요한 데이터를 선정하고, 선정된 데이터를 사용하여 디자인에 적용할 수 있는 형태의 의미있는 데이터로 변환합니다. 디자인에 적용할 수 있는 형태의 데이터에는 설문이나 관찰 조사된 데이터의 분석 보고서도 있고, 데이터의 내용을 시각적으로 표현한 그래프나 다이어그램, 디자이너가 추출한 인사이트, 그리고 디자이너가 제작한 문제의 구조 다이어그램도 있을 것입니다. 또한 디자인 콘셉트를 표현한 스케치나 도면도 데이터가 됩니다. 그리고 이러한 의미있는 디자인 데이터들은 디자이너의 의도에 의하여 목표하는 디바이스나 플랫폼에서 작동하는 화면 레이아웃이나 버튼, 인터렉션을 발생하는 이벤트 등의 디자인 구현 데이터들로 변환되어 디지털 서비스의 개발 코드에 사용됩니다. 결국 데이터의 시각에서 디자인 과정을 해석하면, 디자인이란 디자인 주제와 관련한 다양한 데이터 재료들을 적절한 방법으로 변환하는 과정을 통하여 디자인 해결안을 구축하는 구현 데이터를 생성하는 과정이라고 말할 수 있습니다.

다만 이 과정에서 사용하는 데이터는 내용과 형식면에서 매우 다양하고, 넓은 범위에 있어서, 데이터들을 선정하고, 해석하고, 필요한 형태로 전환하는 작업들이 디자이너의 주관적이고 창의적인 활동 역량에 의존적이라는 특징이 있습니다. 이와같이 기존의 디자인 방법론도 데이터를 사용하여 디자인을 해왔지만, 최근 주목받는 데이터 기반 디자인(Data Driven Design)의 다른 점은 디자인에 사용하는 데이터들을 디지털화 함으로써 대규모의 데이터를 소프트웨어적인 방법으로 통합, 변형하거나 관리하는 것이 가능한 점, 다양하고 생산성 높은 과학적 분석 기법들을 적용할 수 있는 점, 디자인 내부에서 뿐 아니라 여러 관련 분야의 조직들이 협업하여 이 데이터들을 공유하고 재구성할 수 있다는 점이 다릅니다. 데이터 기반 디자인은 디자인 활동의 내용 측면에서는 기존의 디자인 방법과 동일하지만, 프로젝트에 사용하는 데이터를 수집하고, 가공하고, 활용하는 방법에 변화가 따르게 됩니다.

### 데이터와 AI의 관계

최근 디자인을 위한 데이터들이 관심을 받게 된 배경에는 인공지능의 출현이 있습니다. 인공지능 서비스의 본질은 서비스의 제공에 필요한 데이터를 수집하고 이를 인간의 사고 과정과 유사한 데이터 모델로 처리하여 결과를 목표하는 데이터 형식으로 출력하는 과정, 즉 인간이 원하는 가치를 얻어내기 위하여 데이터의 입력, 처리, 출력의 라이프사이클을 인공지능을 사용하여 관리하는 기술이라고 할 수 있는데, 서술하는 바와 같이 인공지능 서비스를 가능하게 하는 기본 재료는 ‘데이터’입니다. 인간의 사고 과정과 유사한 데이터 모델(인공지능)을 구축하기 위하여는 인간이 데이터를 처리하는 방법을 다량의 데이터로 학습하는 과정이 필요합니다. 이러한 학습 과정을 통하여 인공지능은 인간처럼 대화하고, 판단하고, 예측할 수 있게 됩니다. 그리고 학습 데이터의 질과 양에 따라서 인공지능의 능력이 달라지므로, 인공지능의 역량을 높이기 위해서 양질의 데이터를 다량으로 학습시키고, 테스트하는 과정이 동반됩니다. 그러므로 어떤 인공지능 서비스를 개발할 때는 어떤 데이터를 어떻게 학습시켜서 우리가 원하는 능력을 갖는 인공지능 모델을 구축할 지에 대한 기술적인 이해가 필요하고, 인공지능 서비스를 개발하는 디자이너라면 사용자, 인공지능 데이터 모델, 구현 서비스 간의 통합적인 접점을 제공하는 UX디자인을 제시할 수 있어야 합니다. 기존에 사용자와 구현 서비스간의 UX를 디자인하는 일에 인공지능 데이터 모델이라는 요소가 추가되어 더욱 다면적인 UX 디자인이 요구되는 것입니다.

\[그림1\] 다이어그램 추가 필요 (데이터, UX디자인, 서비스, AI)

### UX 디자인 대상으로서의 AI와 UX 디자인 도구로서의 AI

본 교재의 학습 주제는 데이터 기반 디자인이므로 UX 디자인과 AI의 두가지 연결 지점에서 사용하는 데이터의 특징을 살펴보겠습니다. 첫번째 연결 지점은 인공지능 서비스가 UX 디자인의 대상이 되는 경우, 즉 인공지능 서비스 개발을 위한 UX 디자인을 하는 지점입니다. 이 경우에 디자이너가 다루는 데이터는 인공지능 서비스가 학습하고, 테스트하고, 수집하는 사용자 및 서비스 관련 데이터가 디자인의 대상이 됩니다. 보통 디자이너는 인공지능 서비스 개발에서 사용자가 접하는 화면 그래픽(GUI)이나 인터렉션을 디자인하는 업무에 한정된다고 생각하기 쉽지만, 인공지능 서비스가 어떤 사용자 경험을 수집하고 이해해야 효과적인 서비스가 가능한지를 판단하려면 인공지능 모델 개발의 초기 단계부터 UX 디자이너가 참여해야합니다.

디자이너는 인공지능 모델을 구축할 때 인공지능이 학습할 데이터의 내용과 형식에 대하여 이해하고, 서비스의 환경과 사용자 상황에 맞는 학습 데이터를 선정하는 일에 참여합니다. 또한 인공지능 모델이 구축된 후에 성능을 테스트하고, 서비스의 완성도를 검증하는 일에도 참여해야합니다. 그리고 인공지능 서비스가 제공될 때, 사용자가 서비스와 잘 소통하고, 서비스 내용을 이해할 수 있는 사용자 접점을 디자인해야 합니다. 마지막으로 사용자의 피드백데이터를 기반으로 인공지능 모델과 서비스를 개선할 수 있는 디자인을 제시하여 서비스의 성장을 이끌게 됩니다. 이렇게 UX 디자이너는 인공지능 서비스 개발과 운영, 평가의 전반에 사용자 경험을 반영하여 서비스의 질을 확보하는 중요한 역할을 하고, 이를 위하여 서비스 전체 과정에서 사용되고, 생성되는 데이터에 대한 문해력이 필요하고, 인공지능 모델 개발자, 서비스 개발자 등 기술 전문가와의 협업 능력도 요구됩니다. 마찬가지로, 디자이너와의 효과적인 협업을 위하여 기술 전문가들도 사용자 경험과 디자인을 이해하는 역량이 요구되고 있습니다.

![\[그림2\] 사용자의 청취 기록을 분석하여 'Discover Weekly'와 같은 맞춤형 콘텐츠를 제공하는 글로벌 음악 스트리밍 서비스, Spotify(3)](1-2%20UX%20%E1%84%83%E1%85%B5%E1%84%8C%E1%85%A1%E1%84%8B%E1%85%B5%E1%86%AB%E1%84%80%E1%85%AA%20%E1%84%83%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A5,%20AI%20e536b52818b34fc69680f8f78a377d76/%25E1%2584%2589%25E1%2585%25B3%25E1%2584%258F%25E1%2585%25B3%25E1%2584%2585%25E1%2585%25B5%25E1%2586%25AB%25E1%2584%2589%25E1%2585%25A3%25E1%2586%25BA_2024-08-05_%25E1%2584%258B%25E1%2585%25A9%25E1%2584%2592%25E1%2585%25AE_12.39.36.png)

\[그림2\] 사용자의 청취 기록을 분석하여 'Discover Weekly'와 같은 맞춤형 콘텐츠를 제공하는 글로벌 음악 스트리밍 서비스, Spotify(3)

두번째, 인공지능은 UX 디자인을 위한 도구 역할을 할 수 있습니다. 데이터 분석과 시각화, 아이디어 도출, 디자인 레이아웃 제안, 그래픽 시안 제작 등 디자인 프로세스의 여러 활동들이 인공지능 기술을 활용한 디자인 서비스로 제공되고 있고, 디자인하는 인공지능 서비스는 앞으로도 영역을 확장하여 발전해 나갈 것입니다. 인공지능 기술을 활용한 디자인 방법은 디자인의 생산성을 높이는 데 크게 기여하고 있습니다. 인공지능 기술은 디자이너의 사고와 작업 방식을 학습하여 디자이너처럼 데이터를 처리하고 그 결과물을 제안합니다. 이러한 상황에서 디자이너들이 기술을 더 잘 활용하고, 디자인의 역량을 확대하기 위해서는 디자인하는 인공지능 기술들이 데이터를 처리하는 방법을 이해하고 활용할 수 있어야하며, 나아가 인공지능이 더 높은 수준의 디자인 작업을 지원할 수 있도록 디자인 데이터와 디자인 행위를 데이터 기술과 연계하는 방법을 개발할 필요가 있습니다.

아래의 기사는 UX 디자인 업무에 AI 서비스를 사용하는 구체적인 업무 내용과 방법들을 설명하고 있습니다. (4)

[AI for UX: Getting Started](https://www.nngroup.com/articles/ai-ux-getting-started/)

2024년 7월에는 대표적인 UX/UI 표현 도구인 피그마에서 AI 기술을 적극적으로 활용한 디자인과 개발, 프레젠테이션 기능들을 선보였습니다. (5)

[Config 2024에서 발표된 새로운 기능](https://help.figma.com/hc/ko/articles/24037640924823-Config-2024에서-발표된-새로운-기능)

이렇게 UX 디자인에 인공지능 기술이 들어와 디자이너의 업무를 수행하게 된다면 어떤 일들이 벌어질까요? 인공지능이 디자인을 할 수 있으므로 디자이너의 일자리가 없어질까요? 인공지능이 담당할 수 없는 창의적이고, 모험적인 업무에는 소수의 디자이너가 주도하고, 인공지능이 디자이너의 업무를 대신하는 것이 가능한 단순 반복적 디자인 작업이나 패턴화된 디자인 작업은 사람대신 인공지능이 대체하게 될 것입니다. 또 많은 디자이너들은 인공지능에게 할 일을 지시하거나 인공지능의 결과물을 검수하는 일, 그리고 인공지능이 디자인 업무를 할 수 있도록 디자인 업무를 디지털 데이터 중심으로 변환하고, 패턴화하는 일을 하거나, 인공지능에게 학습 데이터를 제공하는 일들을 하게 될 것입니다. 이렇게 인공지능 기반 디자인 도구들은 디자이너의 업무 내용이나 업무 역량의 변화를 이끌고, 디자인 전문가가 아닌 사람들과 디자인 업무의 협업자들이 인공지능 서비스를 활용하여 쉽게 UX 디자인 문제들을 해결하게 할 것으로 예상합니다. 기술은 본래 의식이 없습니다. 기술이 우리에게 긍정적인 역할을 할지, 부정적인 역할을 할지는 인간의 사용 의도에 따라 달라질 수 있습니다. 디자이너는 중립적인 인공지능 기술이 우리에게 유리한 방향으로 기여하도록 잘 이끌어 가야 하겠습니다.

(문헌 3) Spotify(스포티파이), Apple app store

(문헌 4) Kate Moran, Jakob Nielsen, “**AI for UX: Getting Started”,** <https://www.nngroup.com/articles/ai-ux-getting-started/>, (2023)

(문헌 5) Figma Learn, “**Config 2024에서 발표된 새로운 기능”,** [https://help.figma.com/hc/ko/articles/24037640924823-Config-2024에서-발표된-새로운-기능](https://help.figma.com/hc/ko/articles/24037640924823-Config-2024%EC%97%90%EC%84%9C-%EB%B0%9C%ED%91%9C%EB%90%9C-%EC%83%88%EB%A1%9C%EC%9A%B4-%EA%B8%B0%EB%8A%A5), (2024)
