---
format: 
  pdf:
    css: styles.css
---

# 1-3. 데이터 기반 디자인 (Data Driven Design)

데이터 기반 디자인(Data Driven Design)이란 디자인 대상과 관련된 방대한 정량화 데이터를 디자인 설계와 의사 결정의 근거로 활용하는 기법과 정량화 테스트를 통하여 디자인 결과물을 평가, 검증하는 기법을 말합니다.(6) 쉽게 말하면, 데이터에 근거하여 디자인 의사 결정을 수행하는 기법이라고 할 수 있습니다. 데이터 기반 디자인 방법론은 디지털 데이터들을 지속적으로 생산하고 축적하는 웹이나 앱 기반 서비스에 쉽게 적용되기 때문에 구글 등 IT 서비스 기업들이 디지털 서비스의 개발과 운영에 활용하고 있습니다. 현재의 데이터 기반 디자인 연구들은 대부분 인터넷을 통하여 수집된 사용자 로그 데이터를 대상으로 이루어지고 있으나, 점차 사물인터넷(IoT: Internet of Things) 센서 데이터를 사용하는 등 더 다양한 데이터 자원을 활용하는 방향으로 발전하고 있습니다.

데이터 기반 디자인 서비스 및 컨설팅을 제공하는 산업은 증가 추세에 있으며, 디지털 콘텐츠(웹/앱 서비스)의 사용자 로그 데이터를 시각화하여 사용자 유입 분석, 사용 행태 분석, A/B 테스팅 분석 결과를 제공하는 서비스가 주를 이룹니다. 데이터 기반 디자인을 수행하기 위하여 정량적 통계 분석 및 데이터 시각화 서비스를 지원하는 도구 및 컨설팅 비즈니스 사례에는 구글 애널리틱스(Google Analytics), 태블로(Tableau), 어도비 타깃(Adobe Target) 서비스 등이 있으며, 각 서비스에 대하여는 다음 단원에서 자세히 다루도록 하겠습니다. (7)

앞서 인공지능 서비스를 디자인하기 위해서는 디자이너가 데이터에 대한 이해가 풍부해야한다고 설명했는데, 선행 연구에 의하면, 인공지능 서비스 개발을 위하여 디자이너는 서비스 및 사용자 관련 데이터를 원격으로 수집할 수 있는 능력과 수집된 데이터에 대한 정량적이고 정성적인 분석과 시각화를 통하여 사용자 행동을 해석하여 디자인에 반영할 수 있는 능력이 요구됩니다. 그리고 실제로 인공지능 서비스를 개발하는 디자이너들은 데이터 중심의 업무 환경에서 데이터의 기초적 통계 분석, 데이터 시각화, A/B 테스팅 기법을 매우 자주 사용하고 있다고 합니다. 그러므로 연구 팀은 디자이너가 데이터로 생각하고, 데이터로 작업하며, 데이터 전문가들과 소통할 수 있도록 하는 교육 과정을 UX 디자인 교육에 반영해야 한다고 주장하고, 또한 UX, HCI 교육에서 디자이너, 데이터 전문가, 엔지니어, 사용자 연구자 등이 함께 협업하는 학제적 수업을 제공하여 학생들이 협업 능력과 창의성을 기를 수 있도록 해야 한다고 제안하였습니다.(8) 선행 연구에서 제시한 바와 같이, 인공지능 서비스를 디자인하기 위한 데이터 문해력은 데이터 기반 디자인을 수행하기 위해 필요한 역량과 일치하고 있습니다. 데이터 기반 디자인을 공부하면서 인공지능 서비스의 디자인 역량을 함께 준비할 수 있다니, 더욱 기대되지 않나요? 그럼 다음 단원 부터는 구체적으로 데이터 기반 디자인의 방법들을 경험해 볼까요?

(문헌 6) Rochelle King, Elizabeth Churchill, and Caitlin Tan, 『Designing with data』, O’reilly, (2017), pp.3-6

(문헌 7) 이현진, 『데이터 드리븐 디자인』, UX리뷰, (2024), pp.43-44

(문헌 8) Qian Yang, Alex Scuito, John Zimmerman, Jodi Forlizzi, and Aaron Steinfeld, “Investigating How Experienced UX Designers Effectively Work with Machine Learning”, DIS(Design Information Systems)(2018), Hong Kong, pp.585–596
